site_name: Cátedra UNESCO de Transparencia y Acceso a la Información
site_url: https://joseluissanmartinmelio.github.io/unesco_page/
site_description: Cátedra UNESCO dedicada a la investigación en transparencia y acceso a la información pública auspiciado por UNESCO internacional.

theme:
  name: material
  logo: images/icon.png
  favicon: images/icon.png
  language: es
  palette:
    - scheme: default
      primary: #0477BF
      accent: #0583F2
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.smooth_scroll

extra_css:
  - stylesheets/extra.css

nav:
  - Inicio: index.md
  - Quiénes Somos: quienes-somos.md
  - Publicaciones: publicaciones.md
  - Investigación: investigacion.md
  - Transferencia de conocimiento: transferencia_conocimiento.md
  - Contacto: contacto.md